services:
  web:
    image: ghcr.io/ericnsibley/prediction_visualizer:latest
    ports:
      - "8050:8050"

  real_estate_mcp:
    image: ghcr.io/ericnsibley/real_estate_mcp:latest
    ports: 
      - "8060:8060"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - real_estate_mcp

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
